// @ts-check
//  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
 
  htmlSidebar: [
    {
      type: 'autogenerated',
      dirName: 'html', // Aponta para a pasta docs/html
    },
  ],
  cssSidebar: [
    {
      type: 'autogenerated',
      dirName: 'css', // Aponta para a pasta docs/css
    },
  ],
  javascriptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'javascript', // Aponta para a pasta docs/javascript
    },
  ],
};

export default sidebars;
